services:
  postgres-0:
    image: bitnami/postgresql-repmgr:14
    container_name: postgres-0
    ports:
      - "5432:5432"
    env_file:
      - path: ./config/env/.master_env
        required: true
    networks:
      - default

  pgpool:
    image: docker.io/bitnami/pgpool:4
    container_name: pgpool
    user: "1001"
    ports:
      - "5433:5432"
    env_file:
      - path: ./config/env/.pgpool_env
        required: true
    depends_on:
      - postgres-0
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
    driver: bridge
