# promethus.yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['172.31.2.37:9100']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_(cpu|memory|disk|filesystem|network).*'
        action: keep

  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.31.2.37:9308']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'kafka_.*'
        action: keep

  - job_name: 'spark_master_native'
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['172.31.3.183:8085']

  - job_name: 'spark_applications_native'
    metrics_path: '/metrics/applications/prometheus'
    static_configs:
      - targets: ['172.31.3.183:8085']

  - job_name: 'spark_worker-1_native'
    metrics_path: '/metrics/worker/prometheus'
    static_configs:
      - targets: ['172.31.2.37:8086']

  - job_name: 'spark_worker-2_native'
    metrics_path: '/metrics/worker/prometheus'
    static_configs:
      - targets: ['172.31.0.17:8087']